### ISSUE TITLE
Debug the rogue wheel(s)

### ISSUE THREAD

**Issue by mlin9556** [cybercat5436/5436_SwerveDriveDevelopment#7]
One of the wheels operates completely differently from the others. There is also a wheel with a stutter, where it starts and stops as it runs.

**Comment by bignaczak** [comment]
The stutter wheel was resolved by changing out the motor controller.  It was confirmed to only occur on the one wheel (BL) when set to idleMode.Brake.  None of the other wheels were affected similarly.
